version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - bridge
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'megainsight_test'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'megainsight_test'
            MYSQL_USER: 'megainsight_test'
            MYSQL_PASSWORD: 'megainsight_test'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - bridge
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-pmegainsight_test'
            retries: 3
            timeout: 5s
networks:
    bridge:
        driver: bridge
volumes:
    mysql:
        driver: local
